title: yoyocheknow blog
author: yoyocheknow
email: 911dangerous@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  记录一下学习和生活
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /blog

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: yoyocheknow
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: yoyocheknow
    github:  yoyocheknow
    linkedIn: in/志华-张-000861157
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed